BEGIN IMMEDIATE;

UPDATE members SET institution='University of Liège', region='Europe', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: lecturer at the University of Liège and teacher at European School Brussels III. Source: https://www.liege-lettres.be/aikaterini-lefka/'), updated_at=datetime('now') WHERE person_id='SAGP001249';
UPDATE members SET institution='Colorado State University', region='USA Mountain', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Associate Professor of Philosophy, Colorado State University. Source: https://philosophy.colostate.edu/people/amarchie/'), updated_at=datetime('now') WHERE person_id='SAGP000957';
UPDATE members SET institution='University of Wrocław', region='Europe', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Professor, Institute of Philosophy, University of Wrocław. Source: https://wns.uwr.edu.pl/pracownicy-jednostki/?omegaId=UWR22ab0f1a047943619942c6e361a53cb4'), updated_at=datetime('now') WHERE person_id='SAGP001664';
UPDATE members SET institution='University of Central Florida', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Assistant Professor of Philosophy, University of Central Florida. Source: https://cah.ucf.edu/person/brian-reese/'), updated_at=datetime('now') WHERE person_id='SAGP000556';
UPDATE members SET institution='Universidad Nacional de Colombia', region='Latin America and Caribbean', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Assistant Professor of Philosophy since 2025, Universidad Nacional de Colombia. Source: https://orcid.org/0000-0002-9045-8562'), updated_at=datetime('now') WHERE person_id='SAGP001237';
UPDATE members SET institution='University of Geneva', region='Europe', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Ambizione Research Fellow in Philosophy, University of Geneva; Honorary Fellow in Greek at UCL. Source: https://www.unige.ch/lettres/philo/collaborateurs/postdocs/caterina-pello'), updated_at=datetime('now') WHERE person_id='SAGP001257';
UPDATE members SET institution='New York University', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Assistant Professor, Institute for the Study of the Ancient World, New York University. Source: https://bulletins.nyu.edu/undergraduate/liberal-studies/liberal-studies.pdf'), updated_at=datetime('now') WHERE person_id='SAGP000068';
UPDATE members SET institution='Oakland University', region='USA Central', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Assistant Professor of Practice in Philosophy, Oakland University. Source: https://www.oakland.edu/phil/faculty/propson/'), updated_at=datetime('now') WHERE person_id='SAGP000677';
UPDATE members SET institution='Gonzaga University', region='USA Western', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Professor of Philosophy and Philosophy Graduate Program Director, Gonzaga University. Source: https://www.gonzaga.edu/college-of-arts-sciences/about/office-of-the-dean/administration/program-directors'), updated_at=datetime('now') WHERE person_id='SAGP001584';
UPDATE members SET institution='Eötvös Loránd University', region='Europe', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Professor, Eötvös Loránd University; also Associate Professor Emeritus at Central European University. Source: https://www.btk.elte.hu/en/units/department-of-ancient-and-medieval-philosophy'), updated_at=datetime('now') WHERE person_id='SAGP001235';
UPDATE members SET institution='The New School', region='USA Eastern', primary_email='condj411@newschool.edu', notes=trim(coalesce(notes||char(10),'')||'Affiliation and email verified 2026-10-10: Philosophy PhD student, The New School for Social Research. Removed an erroneous trailing > from the stored email. Source: https://www.newschool.edu/nssr/philosophy-current-students/'), updated_at=datetime('now') WHERE person_id='SAGP000073';
UPDATE members SET institution='University of Florida', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Philosophy faculty, University of Florida. Source: https://undergrad.aa.ufl.edu/media/undergradaaufledu/gen-ed/ge-core-syllabi/ge-syllabi-2025/14239.pdf'), updated_at=datetime('now') WHERE person_id='SAGP000346';
UPDATE members SET institution='University of Chicago', region='USA Central', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: currently teaching in the University of Chicago Social Sciences sequence. Source: https://timeschedules.uchicago.edu/view.php?dept=SOSC&term=464'), updated_at=datetime('now') WHERE person_id='SAGP000802';
UPDATE members SET institution='National Autonomous University of Mexico', region='Latin America and Caribbean', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: ancient philosophy, Faculty of Philosophy and Letters, UNAM. Source: https://colegiodefilosofia.filos.unam.mx/maria-teresa-padilla-longoria/'), updated_at=datetime('now') WHERE person_id='SAGP001255';
UPDATE members SET institution='University of Memphis', region='USA Central', notes=trim(coalesce(notes||char(10),'')||'Identity and affiliation verified 2026-10-10: Assistant Professor of Philosophy, University of Memphis; earlier sources connect the stored Gmail address to the same ancient-philosophy scholar. Sources: https://www.memphis.edu/philosophy/people/bios/sean-driscoll.php and https://bostonphenomenologycircle.wordpress.com/'), updated_at=datetime('now') WHERE person_id='SAGP000293';

UPDATE members SET institution='The Catholic University of America', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Recent affiliation verified 2026-10-10: Philosophy postdoctoral scholar, The Catholic University of America. Source: https://cua.academia.edu/DarylLi'), updated_at=datetime('now') WHERE person_id='SAGP000443';
UPDATE members SET institution='Hamline University', region='USA Central', notes=trim(coalesce(notes||char(10),'')||'Last verified academic affiliation: Philosophy, Hamline University. Current status was not confirmed in 2026. Source: https://philpeople.org/profiles/gary-gabor'), updated_at=datetime('now') WHERE person_id='SAGP000733';
UPDATE members SET institution='New York University', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Last verified academic affiliation: instructor at New York University through 2019. Current academic appointment was not confirmed in 2026. Source: https://www.researchgate.net/profile/Gregory-Scott-11'), updated_at=datetime('now') WHERE person_id='SAGP000162';
UPDATE members SET institution='IBM', region='USA Mountain', notes=trim(coalesce(notes||char(10),'')||'Current nonacademic affiliation located 2026-10-10: IBM in Colorado. Former ancient-philosophy PhD at Northwestern University. Source: https://www.linkedin.com/in/haewonito'), updated_at=datetime('now') WHERE person_id='SAGP000806';
UPDATE members SET institution='University of Toronto', region='Canada', notes=trim(coalesce(notes||char(10),'')||'Historical academic affiliation verified: University of Toronto. Current appointment was not confirmed in 2026. Source: https://philosophy.utoronto.ca/wp-content/uploads/2010-PDF-of-Philosophy-News.pdf'), updated_at=datetime('now') WHERE person_id='SAGP001143';
UPDATE members SET institution='University of Oslo', region='Europe', notes=trim(coalesce(notes||char(10),'')||'Last verified academic affiliation: guest researcher and teaching assistant, University of Oslo, following a UCL PhD completed in 2022. Current status was not confirmed in 2026. Source: https://independent.academia.edu/JonathanGriffiths2/CurriculumVitae'), updated_at=datetime('now') WHERE person_id='SAGP001514';
UPDATE members SET institution='University of Toronto', region='Canada', notes=trim(coalesce(notes||char(10),'')||'Last verified academic affiliation: University of Toronto, PhD in Philosophy (2011). No current appointment was confirmed in 2026. Source: https://philpeople.org/profiles/nicholas-riegel'), updated_at=datetime('now') WHERE person_id='SAGP001208';
UPDATE members SET institution='University of Bolton', region='Europe', notes=trim(coalesce(notes||char(10),'')||'Historical academic affiliation verified: Professor of Philosophy, University of Bolton; also associated with University of Manchester research. Current appointment was not confirmed in 2026. Source: https://sunypress.edu/Books/A/Aristotle-s-Philosophy-of-Friendship2'), updated_at=datetime('now') WHERE person_id='SAGP001763';
UPDATE members SET institution='New College of Florida', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Post-retirement affiliation verified: Research Professor, New College of Florida; retired from the University of Kentucky. Current status was not independently confirmed in 2026. Source: https://ncf.academia.edu/ThomasOlshewsky'), updated_at=datetime('now') WHERE person_id='SAGP000550';

COMMIT;
