BEGIN IMMEDIATE;

-- Current academic affiliations verified from institutional or comparably strong sources.
UPDATE members SET display_name='María Angélica Fierro', first_name='María Angélica', last_name='Fierro', institution='University of Buenos Aires / CONICET', region='Latin America and Caribbean', notes=trim(coalesce(notes||char(10),'')||'Name and affiliation verified 2026-10-10: Principal Researcher at CONICET and Adjunct Professor of Ancient Philosophy at the University of Buenos Aires. Source: https://if.institutos.filo.uba.ar/integrante/fierro-mar%C3%ADa-ang%C3%A9lica'), updated_at=datetime('now') WHERE person_id='SAGP001232';
UPDATE members SET institution='New York University', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Visiting Scholar at New York University for 2025-26; Visiting Assistant Professor at Hunter College from 2023 to 2025. Source: https://www.theshepardsonian.com/_files/ugd/76b642_d8ff4ba6e15f41babac2e8292e7951b0.pdf?index=true'), updated_at=datetime('now') WHERE person_id='SAGP000165';
UPDATE members SET institution='Loyola Marymount University', region='USA Western', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Clinical Assistant Professor of Management in the College of Business Administration, with a PhD in Philosophy. Source: https://expertfile.com/organizations/Loyola-Marymount-University/expert/justin.nordinphd/justin-nordin--ph.d.'), updated_at=datetime('now') WHERE person_id='SAGP001089';
UPDATE members SET institution='Tarleton State University', region='USA Central', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Associate Professor of Philosophy and Associate Dean of the Honors College. Source: https://faculty.tarleton.edu/aho/'), updated_at=datetime('now') WHERE person_id='SAGP000868';
UPDATE members SET institution='Marquette University', region='USA Central', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Teaching Assistant Professor in the University Honors Program. Source: https://www.marquette.edu/honors/honors-staff.php'), updated_at=datetime('now') WHERE person_id='SAGP000328';
UPDATE members SET institution='University of Ioannina / University of Crete', region='Europe', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Adjunct Instructor at the University of Ioannina since October 2025 and postdoctoral researcher at the University of Crete since August 2024. Source: https://philosophy.uoi.gr/wp-content/uploads/2025/11/analytiko-cv-en.pdf'), updated_at=datetime('now') WHERE person_id='SAGP001262';
UPDATE members SET institution='National and Kapodistrian University of Athens', region='Europe', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Research Fellow in the Applied Philosophy Research Laboratory; the stored email also appears on a University of Patras faculty page. Sources: https://philosophylab-en.philosophy.uoa.gr/people/senior_researchers and https://philosophy.upatras.gr/en/staff/'), updated_at=datetime('now') WHERE person_id='SAGP001261';
UPDATE members SET institution='Institute of Philosophy, Political Science and Law, National Academy of Sciences of Tajikistan', region='Asia', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10 from the 2025 Upper Midwest AAR program. Source: https://www.bernardopandrade.com/uploads/1/4/0/3/140332369/umw_aar_annual_conference_meeting.pdf'), updated_at=datetime('now') WHERE person_id='SAGP001264';
UPDATE members SET institution='Yale University / University of Padua', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Marie Skłodowska-Curie Postdoctoral Research Fellow based at Yale University and the University of Padua. Source: https://nelc.yale.edu/people/max-bergamo'), updated_at=datetime('now') WHERE person_id='SAGP001233';
UPDATE members SET institution='Iranian Institute of Philosophy', region='Middle East and North Africa', notes=trim(coalesce(notes||char(10),'')||'Identity and affiliation verified 2026-10-10: Mohammad Javad Esmaeili, academic staff at the Iranian Institute of Philosophy and 2025-26 distinguished visitor at the University of Notre Dame. The Notre Dame page confirms the stored email. Source: https://historyofphilosophy.nd.edu/distinguished-visitors/mohammad-javad-esmaeili/'), updated_at=datetime('now') WHERE person_id='SAGP001243';
UPDATE members SET institution='St. Louis Community College', region='USA Central', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: Associate Professor of Philosophy at St. Louis Community College-Meramec. Current professional name also appears as Sahar Joakim Resch. Sources: https://philosophy.ucla.edu/alumnus/sahar-joakim/ and https://www.saharjoakim.net/research.html'), updated_at=datetime('now') WHERE person_id='SAGP001060';
UPDATE members SET institution='Humber Polytechnic', region='Canada', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: listed in Humber Polytechnic faculty service records for Liberal Arts and Sciences, updated February 2025. Source: https://humber.ca/peoples-and-culture/assets/files/compensation-and-benefits/Academic-Partial-Load-Service-Credit-List.pdf'), updated_at=datetime('now') WHERE person_id='SAGP001201';

-- Current nonacademic, independent, and school affiliations.
UPDATE members SET institution='The Wylie Agency', region='Europe', notes=trim(coalesce(notes||char(10),'')||'Current nonacademic affiliation located 2026-10-10: The Wylie Agency in London, following an MSt in Ancient Philosophy at Oxford in 2024-25. Source: https://uk.linkedin.com/in/catherine-borthwick-40a4a6222'), updated_at=datetime('now') WHERE person_id='SAGP001236';
UPDATE members SET institution='The Nightingale-Bamford School', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10: teacher and ancient-philosophy researcher at The Nightingale-Bamford School; also presented as New York University at the 2025 SAGP conference. Sources: https://www.apaonline.org/resource/resmgr/eastern2025/E2025_Meeting_Program_Draft.pdf and https://societyforancientgreekphilosophy.org/events/annual-conference/2025/'), updated_at=datetime('now') WHERE person_id='SAGP000138';
UPDATE members SET institution='Apple', region='USA Western', notes=trim(coalesce(notes||char(10),'')||'Current nonacademic affiliation located 2026-10-10: audio technology work at Apple; identity corroborated by recent Apple patent records. Sources: https://www.linkedin.com/in/dersheet-mehta-aa20266 and https://patents.justia.com/inventor/dersheet-c-mehta'), updated_at=datetime('now') WHERE person_id='SAGP001025';
UPDATE members SET institution='Palmetto Family Council', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Current nonacademic affiliation verified 2026-10-10: Publishing and Advocacy Director, Palmetto Family Council. Source: https://www.palmettofamily.org/team'), updated_at=datetime('now') WHERE person_id='SAGP001820';
UPDATE members SET institution='XMPP Standards Foundation / independent scholar', region='USA Mountain', notes=trim(coalesce(notes||char(10),'')||'Current nonacademic/independent status verified 2026-10-10: former technology professional, independent writer, and Treasurer of the XMPP Standards Foundation. Sources: https://beautifulwisdom.substack.com/p/meanwhile-back-at-the-ranch and https://liberapay.com/stpeter/'), updated_at=datetime('now') WHERE person_id='SAGP000983';
UPDATE members SET institution='Independent scholar', region='USA Central', notes=trim(coalesce(notes||char(10),'')||'Last verified professional status: independent scholar, as identified in the Society for Phenomenology and Existential Philosophy program. No current institutional appointment was found in the 2026 search. Source: https://www.spep.org/website/wp-content/uploads/2010/09/Program2002.pdf'), updated_at=datetime('now') WHERE person_id='SAGP000812';

-- Historical or former affiliations: retained with explicit qualification in notes.
UPDATE members SET institution='University of Bergen', region='Europe', notes=trim(coalesce(notes||char(10),'')||'Last verified academic affiliation: University of Bergen, where the member completed a PhD in Philosophy in 2015. A third-party profile suggests later study at Western Norway University of Applied Sciences, but no current institutional page was located. Source: https://www.uib.no/sites/w3.uib.no/files/attachments/innkalling_08.09.15_2.pdf'), updated_at=datetime('now') WHERE person_id='SAGP001401';
UPDATE members SET institution='University of Illinois Chicago', region='USA Central', notes=trim(coalesce(notes||char(10),'')||'Historical affiliation located 2026-10-10: Professor Emeritus of English at the University of Illinois Chicago. Current activity was not independently confirmed. Source: https://uic.academia.edu/DonaldGMarshall'), updated_at=datetime('now') WHERE person_id='SAGP001075';
UPDATE members SET institution='University of Maryland Global Campus', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Last verified academic affiliation: appointed Adjunct Assistant Professor at the institution then named University of Maryland University College in 2010. No current appointment was confirmed in 2026. Source: https://philjobs.org/appointments/index?max=1000&offset=5007'), updated_at=datetime('now') WHERE person_id='SAGP000379';
UPDATE members SET institution='University of Pennsylvania', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Historical affiliation verified: Director of Professional Education at the Fels Institute and teacher in Government Administration and Classical Studies at the University of Pennsylvania. Current status was not confirmed in 2026. Source: https://orb.binghamton.edu/sagp/342/'), updated_at=datetime('now') WHERE person_id='SAGP000331';
UPDATE members SET institution='Lone Star College-University Park', region='USA Central', notes=trim(coalesce(notes||char(10),'')||'Last verified academic affiliation: adjunct philosophy faculty at Lone Star College-University Park in 2018. No current appointment was confirmed in 2026. Source: https://govsalaries.com/salaries/adjunct-faculty-philosophy-salary-lookup/texas'), updated_at=datetime('now') WHERE person_id='SAGP000946';
UPDATE members SET institution='Butler University', region='USA Central', notes=trim(coalesce(notes||char(10),'')||'Former academic affiliation: Associate Professor and department chair at Butler University. Employment there ended in January 2022; no current academic affiliation was confirmed in 2026. Source: https://thebutlercollegian.com/2022/01/former-butler-university-professor-arrested-on-child-pornography-charges/'), updated_at=datetime('now') WHERE person_id='SAGP000675';

COMMIT;
