BEGIN IMMEDIATE;

UPDATE members SET institution='McIntosh High School', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Affiliation verified 2026-10-10 from the exact stored Fayette County Board of Education email: faculty club sponsor at McIntosh High School. Source: https://mhs.fcboe.org/resources/clubs-and-organizations/social-studies-clubs'), updated_at=datetime('now') WHERE person_id='SAGP000510';

UPDATE members SET institution='University of California, Merced', region='USA Western', notes=trim(coalesce(notes||char(10),'')||'Identity and current affiliation verified 2026-10-10: Associate Teaching Professor of Philosophy at UC Merced, specializing in ancient and moral philosophy. The stored Gmail and UC Merced affiliation also appear together in the 2018 SAGP program. Sources: https://philosophy.ucmerced.edu/content/david-jennings and https://www.researchgate.net/publication/326260797_SAGP_2018_-_Draft_Program'), updated_at=datetime('now') WHERE person_id='SAGP001058';

UPDATE members SET institution='Binghamton University', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Last verified academic affiliation: Comparative Literature instructor and graduate scholar at Binghamton University in 2017-18. More recent publication activity confirms continuing independent scholarship, but no current employing institution was established. Sources: https://www.buffalo.edu/content/dam/www/nemla/programs/NeMLA%202017%20Convention%20Program.pdf and https://www.tcd.ie/literary-translation/assets/doc/TCLCT%202022-23%20Newsletter.pdf'), updated_at=datetime('now') WHERE person_id='SAGP000357';

UPDATE members SET institution='Seoul National University', primary_email='les99@snu.ac.kr', region='Asia', notes=trim(coalesce(notes||char(10),'')||'Identity, current affiliation, and email verified 2026-10-10: Associate Professor of Philosophy at Seoul National University; Stanford PhD in Classics. Source: https://www.tandfonline.com/doi/full/10.1080/00029890.2026.2697710'), updated_at=datetime('now') WHERE person_id='SAGP001034';

UPDATE members SET institution='University of Kentucky', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Last verified academic affiliation: University of Kentucky, as listed in the 2020 Ancient Philosophy Society program. Earlier appointments included the University of Minnesota Duluth and Boston University. No current appointment was confirmed in the 2026 search. Source: https://www.ancientphilosophysociety.org/website/wp-content/uploads/2020/01/APS-2020-Program-Near-Final-1.pdf'), updated_at=datetime('now') WHERE person_id='SAGP001701';

UPDATE members SET display_name='Luigi Bradizza', first_name='Luigi', last_name='Bradizza', institution='Salve Regina University', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Formal name and current affiliation verified 2026-10-10: Professor and Chair of Political Science and International Relations at Salve Regina University. Source: https://www.salve.edu/our-mission/faculty-staff-directory/dr-luigi-bradizza'), updated_at=datetime('now') WHERE person_id='SAGP001397';

UPDATE members SET institution='Independent writer and editor', region='USA Eastern', notes=trim(coalesce(notes||char(10),'')||'Current nonacademic professional status verified 2026-10-10 from the exact stored email: poet, fiction and nonfiction writer, teacher, and literary-journal editor based in North Charleston. Source: https://www.pw.org/directory/writers/maria_s_picone'), updated_at=datetime('now') WHERE person_id='SAGP000460';

UPDATE members SET display_name='Mariusz Węgrzyn', first_name='Mariusz', last_name='Węgrzyn', institution='John Paul II Catholic University of Lublin', region='Europe', notes=trim(coalesce(notes||char(10),'')||'Name and last verified academic affiliation established from the exact stored email: philosophy graduate of the Catholic University of Lublin and cultural philosopher, journalist, and public-relations consultant. Current employment was not confirmed in 2026. Sources: https://ojs.tnkul.pl/index.php/rkult/article/download/8339/9012/ and https://www.welz.eu/esa/members.html'), updated_at=datetime('now') WHERE person_id='SAGP001797';

UPDATE members SET institution='Liceo Classico Tommaso Gargallo', region='Europe', notes=trim(coalesce(notes||char(10),'')||'Current affiliation verified 2026-10-10 from the exact stored email: professor and organizer of the 2026 Certamen Latinum Syracusanum at Liceo Classico Tommaso Gargallo in Syracuse. Source: https://www.istruzioneer.gov.it/2026/02/23/certamen-latinum-syracusanum-mmxxvi-editio-xxxviii/?download=86502'), updated_at=datetime('now') WHERE person_id='SAGP001601';

UPDATE members SET institution='International Society for Astrological Research', region='USA Western', notes=trim(coalesce(notes||char(10),'')||'Last verified professional affiliation from the exact stored email: advisor to the International Society for Astrological Research in 2016-17. No more recent organizational role was confirmed in 2026. Source: https://isarastrology.com/wp-content/uploads/2022/08/Series-46-Vol-3.pdf'), updated_at=datetime('now') WHERE person_id='SAGP001070';

UPDATE members SET display_name='Nicholas Rose', first_name='Nicholas', last_name='Rose', institution='Nicholas Rose & Associates', region='Europe', notes=trim(coalesce(notes||char(10),'')||'Name order and current nonacademic affiliation verified 2026-10-10 from the exact stored domain email: UKCP-registered counsellor and psychotherapist at Nicholas Rose & Associates. Sources: https://www.nicholas-rose.co.uk/specialities/celebrity-fame-high-public-profile-and-wealth and https://existentialanalysis.org.uk/wp-content/uploads/2020/10/SEA-LIST-OF-REGISTRANTS.pdf'), updated_at=datetime('now') WHERE person_id='SAGP001259';

UPDATE members SET display_name='George Wendell', first_name='George', last_name='Wendell', institution='Guaranty Lease Funding Corporation', notes=trim(coalesce(notes||char(10),'')||'Name order and historical professional affiliation verified 2026-10-10. Miami records identify George Wendell as president of Guaranty Lease Funding Corporation and describe his occupation as attorney/banker or businessman. The corporation is inactive and no current employer was confirmed. Identity is corroborated by recent Coral Gables/Miami community and family records. Sources: https://bizstanding.com/directory/FL/GU/94/ ; https://www.citynmb.com/DocumentCenter/View/1611/Gary-Goldman-PDF ; https://alhambraorchestra.org/wp-content/uploads/AlhOrchNwsltr_Summer2023.pdf ; https://www.dignitymemorial.com/obituaries/miami-fl/edward-wendell-12772094'), updated_at=datetime('now') WHERE person_id='SAGP000579';

COMMIT;
